services:

  cache:
    image: redis:6.2-alpine
    restart: always
    networks:
      - api
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "${EXPOSED_DB_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    networks:
      - api

  api:
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
    container_name: monkeyradio-api
    ports:
      - "${EXPOSED_API_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - api
    volumes:
      - ./:/app
    command: npm run start:dev

  s3:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "${EXPOSED_S3_PORT}:9000"
    volumes:
      - minio_data:/data
    networks:
      - api
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data

networks:
  api:

volumes:
  mongo_data:
  minio_data: