version: "3.7"

services:

  redis:
    image: redis:alpine
    restart: no
    networks:
      - backend

  mongo:
    image: mongo
    restart: no
    networks:
      - backend
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: noworry
      MONGO_INITDB_ROOT_PASSWORD: itsalocalapp
    command: mongod --auth --quiet --logpath /dev/null 

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    restart: no
    env_file: ./.env
    environment:
      MONGODB_URI: "mongodb://noworry:itsalocalapp@mongo"
      REDIS_HOST: "redis"
      ROUTE_SRC: "./src/routes/"
    ports:
      - 9229:9229
    depends_on:
      - mongo
      - redis
    networks:
      - backend

networks:
  backend:
